spring.application.name=HotelManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel1DB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.session.jdbc.initialize-schema=always
spring.jpa.show-sql=true
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = krups0628@gmail.com
spring.mail.password = jyyzjqfmgnitbdyk

spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true